config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('platform_student.urls')),
    path('users/', include('users.urls', namespace='users')),

]

platform_student/urls.py
from django.urls import path
from . import views
from platform_student.views import index, MaterialDetailView, QuizView, check_answer
from platform_student.apps import LearningPlatformConfig


app_name = LearningPlatformConfig.name


urlpatterns = [
    path('', index, name='index'),
    path('material_list/<int:section_id>/', views.material_list, name='material_list'),
    path('material_detail/<int:pk>/', MaterialDetailView.as_view(), name='material_detail'),
    path('check_answer/', check_answer, name='check_answer'),
    path('quiz/<int:material_id>/', QuizView.as_view(), name='quiz'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

platform_student/models.py
from django.db import models
NULLABLE = {'blank': True, 'null': True}


class Section(models.Model):
    """Модель секции"""
    name = models.CharField(max_length=255, verbose_name="Название секции")
    description = models.TextField(verbose_name="Описание секции", max_length=110,  **NULLABLE)


class Material(models.Model):
    """Модель Материала. В каждой секции, есть несколько статей(материал для изучения)"""
    section = models.ForeignKey(Section, on_delete=models.CASCADE, verbose_name="Название секции")
    title = models.CharField(max_length=255, verbose_name="название")
    content = models.TextField(verbose_name="контент")
    summary = models.TextField(verbose_name="Краткое содержание", **NULLABLE)

    def __str__(self):
        return f'{self.title}, {self.content}'

    class Meta:
        verbose_name = "материал"
        verbose_name_plural = "материалы"


class Test(models.Model):
    """Модель Тест. В каждом матере есть тесть, который поможет проверить знания псоле прочитанного"""
    material = models.ForeignKey(Material, on_delete=models.CASCADE, verbose_name="материал")
    question = models.CharField(max_length=255, verbose_name="вопрос")
    option1 = models.CharField(max_length=255, **NULLABLE)
    option2 = models.CharField(max_length=255, **NULLABLE)
    option3 = models.CharField(max_length=255, **NULLABLE)
    correct_answer = models.CharField(max_length=255, verbose_name="правильный оответ", choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')])

    def __str__(self):
        return f'{self.question}, {self.correct_answer}'

    class Meta:
        verbose_name = "тест"
        verbose_name_plural = "тесты"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "password", "first_name", "last_name"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

platform_student/views.py
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from django.views import View

from platform_student.models import Section, Material, Test
from django.views.generic import DetailView


def index(request):
    """Главная страница"""
    section_list = Section.objects.all()
    context = {
        'section_list': section_list
    }
    return render(request, "platform_student/base.html", context)


def material_list(request, section_id):
    """Страница с Материалами"""
    section = Section.objects.get(pk=section_id)
    materials = Material.objects.filter(section=section)
    return render(request, 'platform_student/material_list.html', {'section': section, 'materials': materials})


class MaterialDetailView(DetailView):
    """Модель детального просмотра материала на странице"""
    model = Material


class QuizView(View):
    template_name = 'platform_student/quiz.html'

    def get(self, request, material_id):
        questions = Test.objects.filter(material_id=material_id)
        context = {'questions': questions}
        return render(request, self.template_name, context)


def check_answer(request):
    if request.method == 'POST':
        # Получаем ответы из формы
        answers = {}
        for key, value in request.POST.items():
            if key.startswith('question'):
                question_id = key.replace('question', '')
                answers[int(question_id)] = value

        # Получаем правильные ответы из базы данных
        correct_answers = {}
        for question in Test.objects.all():
            if question.correct_answer == 'option2':
                correct_option_value = question.option2
            elif question.correct_answer == 'option3':
                correct_option_value = question.option3
            else:
                correct_option_value = question.option1

            correct_answers[question.id] = correct_option_value

        # Проводим проверку ответов
        correct_count = 0
        incorrect_answers = []  # Создаем список для неверных ответов

        for question_id, user_answer in answers.items():
            correct_answer = correct_answers.get(question_id, '')
            if str(user_answer) == str(correct_answer):
                correct_count += 1
            else:
                # Если ответ неверный, добавляем в список
                question = Test.objects.get(pk=question_id)
                incorrect_answers.append({
                    'question': question.question,
                    'user_answer': user_answer,
                    'correct_answer': correct_answer
                })

        # Возвращаем результат в шаблон
        return render(request, 'platform_student/check_answer.html', {
            'correct_count': correct_count,
            'incorrect_answers': incorrect_answers
        })

    # Если запрос не POST, перенаправляем на главную страницу или возвращаем ошибку
    return HttpResponseBadRequest('Invalid request method')

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserForm
from users.models import User


# Create your views here.


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class ProfileView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

platform_student/templates/platform_student/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            overflow-x: hidden;
            transition: margin-left 0.5s;
        }

        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #212529;
            color: white;
            overflow-y: auto;
            transition: 0.5s;
            padding-top: 60px;
            border-color: #343a40;
        }

        .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color: #212529;
            color: white;
            padding: 10px 15px;
            border: none;
            border-color: #64707d;
        }

        .openbtn:hover {
            background-color: #64707d;
        }

        .sidebar a {
            padding: 10px 15px;
            text-decoration: none;
            font-size: 18px;
            color: white;
            display: block;
            transition: 0.3s;
            margin-bottom: 10px;

        }

        .sidebar a:hover {
            background-color: #64707d;
        }

        .content-container {
            transition: margin-left 0.5s;
            background-color: #64707d;
            color: #64707d;
        }

        .d-flex {
            margin-left: 0;
        }
    </style>
</head>
<body>

<!-- Кнопка для открытия бокового меню -->
<button class="openbtn" onclick="openNav()">☰ Меню</button>

<!-- Боковое меню -->
<div id="mySidebar" class="sidebar">
    <a href="javascript:void(0)" class="p-2 closebtn text-center" onclick="closeNav()">Выйти из меню</a>
    <a href="{% url 'platform_student:index' %}" class="p-2 btn btn-dark">Главная страница</a>
    {% if user.is_authenticated %}
    <a href="{% url 'users:logout' %}" class="p-2 btn btn-dark" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>
    <a class="p-2 btn btn btn-dark" href="{% url 'users:profile' %}">Профиль</a>

<form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
    {% csrf_token %}
</form>
{% else %}
    <a href="{% url 'users:login' %}" class="p-2 btn btn-dark">Войти</a>
    <a class="p-2 btn btn-dark" href="{% url 'users:register' %}">Регистрация</a>
{% endif %}
</div>


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <main class="container">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-15 fst-italic">Добро пожаловать в мир самообучения</h1>
      <p class="lead my-3">Проект создан с целью помощи студентам в их самостоятельном обучении и развитии</p>
      <p class="lead mb-0"><a href="#" class="text-white fw-bold">Все получится!</a></p>
    </div>
  </div>
 {% block content %}
    <div class="row mb-2">
        {% for section in section_list %}
            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary">know the world</strong>
                        <h3 class="mb-0">{{ section.name }}</h3>
                        <div class="mb-1 text-muted">Это интересно</div>
                        <p class="card-text mb-auto">{{ section.description }}</p>
                        <a href="{% url 'platform_student:material_list' section.id %}" class="stretched-link">Перейти</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c" />
                            <text x="20%" y="20%" fill="#eceeef" dy=".3em">Все получится</text>
                        </svg>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

</div>
</div>
</div>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#top">Вернуться в начало</a>
        </p>
        <p>{% now 'Y' %}</p>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!-- JavaScript для открытия/закрытия бокового меню -->
<script>
    function openNav() {
        document.getElementById("mySidebar").style.width = "250px";
        document.body.style.marginLeft = "250px";
    }

    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.body.style.marginLeft = "0";
    }
</script>

</body>
</html>

platform_student/templates/platform_student/check_answer.html
{% extends 'platform_student/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 border border-secondary rounded p-4 mt-4 bg-light">
                <h2 class="text-center">Результат теста</h2>

                {% if correct_count == total_questions %}
                    <p class="text-success text-center">Поздравляем! Вы правильно ответили на все {{ total_questions }} вопросов.</p>
                {% else %}
                    <p class="text-center">Вы правильно ответили на {{ correct_count }} из {{ total_questions }} вопросов.</p>

                    {% if incorrect_answers %}
                        <h3 class="text-center">Неверные ответы:</h3>
                        <ul>
                            {% for answer in incorrect_answers %}
                                <li>
                                    <strong>Вопрос:</strong> {{ answer.question }}<br>
                                    <strong>Ваш ответ:</strong> {{ answer.user_answer }}<br>
                                </li>
                                <hr class="my-2">
                            {% endfor %}
                        </ul>

                        <p class="text-danger text-center">
                            Прочитайте повторно материал и попробуйте пройти тест повторно. У вас все получится!
                        </p>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

platform_student/templates/platform_student/material_detail.html
{% extends 'platform_student/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 border rounded p-4 mt-4 bg-light" style="background-color: #d3d7db; border-color: #64717d; color: #212529;">
            <h2 class="text-center">{{ object.title }}</h2>
            <p class="text-center">{{ object.content }}</p>
            <a href="{% url 'platform_student:quiz' material_id=object.id %}" class="btn btn-primary mt-3" style="background-color: #64717d; border-color: #64717d;">Пройти тест</a>
        </div>
    </div>
</div>
{% endblock %}

platform_student/templates/platform_student/material_list.html
{% extends 'platform_student/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="row mb-2">
            {% for material in materials %}
                <div class="col-md-6">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block mb-2 text-primary">Сeкция: {{ material.section.name }}</strong>
                            <h3 class="mb-0">{{ material.title }}</h3>
                            <div class="mb-1 text-muted">Nov 12</div>
                            <p class="card-text mb-auto">{{ material.summary }}</p>
                            <a href="{% url 'platform_student:material_detail' material.id %}" class="stretched-link">Перейти</a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                                <title>Placeholder</title>
                                <rect width="100%" height="100%" fill="#55595c" />
                                <text x="20%" y="20%" fill="#eceeef" dy=".3em">Все получится</text>
                            </svg>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Для доступа к этой информации необходимо <a href="{% url 'users:login' %}">войти</a> или <a href="{% url 'users:register' %}">зарегистрироваться</a>.</p>
    {% endif %}
{% endblock %}

platform_student/templates/platform_student/quiz.html
{% extends 'platform_student/base.html' %}

{% block content %}
    <h2 class="mb-4">Тест</h2>
    <form method="post" action="{% url 'platform_student:check_answer' %}">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                {% for question in questions %}
                    <div class="col-md-6">
                        <div class="card mb-4">
                            <div class="card-body">
                                <legend class="text-left">{{ question.question }}</legend>
                                <label class="form-check">
                                    <input type="radio" name="question{{ question.id }}" value="{{ question.option1 }}" class="form-check-input"> {{ question.option1 }}
                                </label><br>
                                <label class="form-check">
                                    <input type="radio" name="question{{ question.id }}" value="{{ question.option2 }}" class="form-check-input"> {{ question.option2 }}
                                </label><br>
                                <label class="form-check">
                                    <input type="radio" name="question{{ question.id }}" value="{{ question.option3 }}" class="form-check-input"> {{ question.option3 }}
                                </label><br>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Проверить ответы</button>
    </form>
{% endblock %}

users/templates/users/login.html
{% extends 'platform_student/base.html' %}

{% block content%}

        <div class="col-16">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-3">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'platform_student/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-3">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'platform_student/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-4"></div>
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                <h6>Профиль пользователя</h6>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}